# Merge 12SL Features with PTB-XL Labels

The goal is to create one dataset that can later be used for model training.

## 1. Import libraries

In [5]:
import pandas as pd

## 2. Set file paths

In [6]:
features_path = "../data/ptb-xl-plus/12sl_features.csv"
labels_path = "../data/ptb-xl-plus/ptbxl_statements.csv"

## 3. Load datasets

In [7]:
df_features = pd.read_csv(features_path)
df_labels = pd.read_csv(labels_path)

df_features.head()

,P_Area_I,P_PeakTime_I,Q_Area_I,Q_PeakTime_I,R_Area_I,R_PeakTime_I,S_Area_I,S_PeakTime_I,QRS_Balance_I,T_Area_I,...,T+_Dur_aVF,T-_Dur_aVF,T+_Amp_aVF,T-_Amp_aVF,T_Morph_aVF,T_DurFull_aVF,P_Dur_Global,P_Found_Global,HR__Global,P_Term_V1
0,0.264,64.0,0.000,0.0,0.737,30.0,0.000,0.0,629.0,0.819,...,208.0,0.0,0.151,0.000,1,208.0,112.0,1,64.0,0.000
1,-0.047,6.0,0.015,8.0,0.794,36.0,1.246,76.0,205.0,2.206,...,0.0,127.0,0.000,-0.078,-1,127.0,66.0,1,75.0,0.000
2,0.000,0.0,0.000,0.0,0.792,38.0,1.389,74.0,141.0,1.155,...,0.0,66.0,0.000,-0.078,-1,66.0,NaN,0,169.0,0.000
3,0.196,74.0,0.000,0.0,0.947,56.0,0.000,0.0,439.0,-0.339,...,0.0,0.0,0.000,0.000,-1,0.0,114.0,1,79.0,0.000
4,0.287,102.0,0.000,0.0,1.021,36.0,0.000,0.0,937.0,0.756,...,104.0,66.0,39.000,-0.034,-2,170.0,136.0,1,92.0,6.612

In [8]:
df_labels.head()

,ecg_id,scp_codes,scp_codes_ext,scp_codes_ext_snomed
0,1,"[('NORM', 100.0), ('LVOLT', 100.0), ('SR', 100...","[('NORM', 100.0), ('LVOLT', 100.0), ('SR', 100...","[(320536, 100.0), (441840, 100.0), (4008453, 1..."
1,2,"[('NORM', 80.0), ('SBRAD', 100.0)]","[('NORM', 80.0), ('SBRAD', 100.0)]","[(134057, 100.0), (321588, 100.0), (440142, 10..."
2,3,"[('NORM', 100.0), ('SR', 100.0)]","[('NORM', 100.0), ('SR', 100.0)]","[(441840, 100.0), (4008453, 100.0), (4010019, ..."
3,4,"[('NORM', 100.0), ('SR', 100.0)]","[('NORM', 100.0), ('SR', 100.0)]","[(441840, 100.0), (4008453, 100.0), (4010019, ..."
4,5,"[('NORM', 100.0), ('SR', 100.0)]","[('NORM', 100.0), ('SR', 100.0)]","[(441840, 100.0), (4008453, 100.0), (4010019, ..."

## 4. Check common identifier

In [9]:
"ecg_id" in df_features.columns, "ecg_id" in df_labels.columns

(True, True)

Both datasets contain `ecg_id`, so this column can be used to connect features with labels.

## 5. Merge datasets

We merge both datasets using the `ecg_id` column.
Each row should contain ECG features and the matching diagnostic labels.

In [10]:
df_merged = pd.merge(df_features, df_labels, on="ecg_id", how="inner")

df_merged.head()

,P_Area_I,P_PeakTime_I,Q_Area_I,Q_PeakTime_I,R_Area_I,R_PeakTime_I,S_Area_I,S_PeakTime_I,QRS_Balance_I,T_Area_I,...,T-_Amp_aVF,T_Morph_aVF,T_DurFull_aVF,P_Dur_Global,P_Found_Global,HR__Global,P_Term_V1,scp_codes,scp_codes_ext,scp_codes_ext_snomed
0,0.264,64.0,0.000,0.0,0.737,30.0,0.000,0.0,629.0,0.819,...,0.000,1,208.0,112.0,1,64.0,0.000,"[('NORM', 100.0), ('LVOLT', 100.0), ('SR', 100...","[('NORM', 100.0), ('LVOLT', 100.0), ('SR', 100...","[(320536, 100.0), (441840, 100.0), (4008453, 1..."
1,-0.047,6.0,0.015,8.0,0.794,36.0,1.246,76.0,205.0,2.206,...,-0.078,-1,127.0,66.0,1,75.0,0.000,"[('CRBBB', 100.0), ('SARRH', 100.0)]","[('CRBBB', 100.0), ('SARRH', 100.0)]","[(134057, 100.0), (313791, 100.0), (314059, 10..."
2,0.000,0.0,0.000,0.0,0.792,38.0,1.389,74.0,141.0,1.155,...,-0.078,-1,66.0,NaN,0,169.0,0.000,"[('CRBBB', 100.0), ('AFIB', 100.0)]","[('CRBBB', 100.0), ('AFIB', 100.0)]","[(134057, 100.0), (313217, 100.0), (313791, 10..."
3,0.196,74.0,0.000,0.0,0.947,56.0,0.000,0.0,439.0,-0.339,...,0.000,-1,0.0,114.0,1,79.0,0.000,"[('ASMI', 100.0), ('ISCAL', 100.0), ('LAFB', 1...","[('ASMI', 100.0), ('ISCAL', 100.0), ('LAFB', 1...","[(134057, 100.0), (313791, 100.0), (316998, 10..."
4,0.287,102.0,0.000,0.0,1.021,36.0,0.000,0.0,937.0,0.756,...,-0.034,-2,170.0,136.0,1,92.0,6.612,"[('NDT', 100.0), ('SR', 100.0)]","[('NDT', 100.0), ('SR', 100.0)]","[(320536, 100.0), (441840, 100.0), (4008453, 1..."

## 6. Check merged dataset shape

In [11]:
df_merged.shape

(21799, 786)

The merged dataset contains ECG features and diagnostic labels in one table.
This dataset can be used in the next step to prepare a target label for classification.

## 7. Save merged dataset

We save the merged dataset to a CSV file for later use.

In [12]:
df_merged.to_csv("../data/processed/merged_12sl_ptbxl.csv", index=False)